feat(): builder container support hidden wrapper
easyops-cn/next-basics pull request #1046
Opened 2022-02-25 10:41 UTC by SailorF

Refs: NEXT_BUILDER-1425

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [x] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2022-02-28 02:02 UTC, weareoutman requested changes

2022-02-28 02:02 UTC, weareoutman commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +  themeId,
还有下面的 `themeList` 也没看懂是什么。

2022-02-28 02:02 UTC, weareoutman commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +  createProviderClass(ReplaceSingleThemePage)
我建议这个 PR 先不要包含这个替换主题的逻辑了。这里的需求不着急，而且逻辑上还有待探讨。

2022-02-28 02:13 UTC, SailorF commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +  themeId,
是的, themeId就是template的名字, themeList是主题模板列表

2022-02-28 02:13 UTC, SailorF commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +          mountPoint: isRoute ? "bricks" : "content",
目前就是一刀切的, 所以建议在创建template的时候需要暴露出一个content的插槽

2022-02-28 02:13 UTC, SailorF commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +          action: "替换",
我改下

2022-02-28 02:13 UTC, SailorF commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +  createProviderClass(ReplaceSingleThemePage)
好的, 我晚点撤回这个commit

2022-02-28 02:13 UTC, SailorF commented on bricks/next-builder/src/data-providers/ReplaceSingleThemePage.ts
> +    );
感觉这种场景应该不存在, 一个页面同时使用多个页面模板?

2022-03-01 06:39 UTC, weareoutman commented
![image](https://user-images.githubusercontent.com/2338946/156118041-e38d57a0-0d6b-4ec9-a860-b20d52f78aef.png)
@SailorF 不更新依赖吗？

2022-03-01 06:44 UTC, SailorF commented
依赖更新了 @weareoutman

2022-03-01 06:44 UTC, weareoutman approved these changes

2022-03-01 06:52 UTC, merged