feat(general-select): 添加title属性
easyops-cn/next-basics pull request #1282
Opened 2022-05-11 12:17 UTC by ningkehua

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2022-05-12 02:27 UTC, SailorF requested changes

2022-05-12 02:27 UTC, SailorF commented on bricks/forms/src/general-select/GeneralSelect.spec.tsx
> +  it("should be no title", () => {
不需要两个用例, 可以合并成一个, 将getSelectWidth mock成一个函数, 根据label的长度返回宽度, 在一个用例里面就可以覆盖到哪些options有title, 哪些没有title

2022-05-12 02:27 UTC, SailorF commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +      setInputWidth(width);
setInputWidth没有必要, 你这里只需要在getTitle中进行宽度对比就可以了, 可以在getTitle中通过getBoundingClientRect直接获取宽度

2022-05-12 02:27 UTC, SailorF commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +    <div ref={ref} style={{ display: "inline-block" }}>
没有比较初始化display: inline-block, 这个可以干掉

2022-05-13 07:54 UTC, weareoutman commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +import * as GeneralSelectModule from "./GeneralSelect";
为什么要 import 自己。。

2022-05-13 07:55 UTC, weareoutman commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +  context.font = `${size} Arial`;
font 都不匹配，这个计算可能是不准的。

2022-05-13 07:56 UTC, weareoutman commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +  context.font = `${size} Arial`;
另外，创建 canvas 的开销是比较大的，每次 Select 重新渲染似乎都会走到这个逻辑，能加上缓存能力吗？

2022-05-13 08:43 UTC, ningkehua commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +import * as GeneralSelectModule from "./GeneralSelect";
> 为什么要 import 自己。。

因为select组件使用了组件外一个方法getSelectWidth（这个方法包含canvas），而canvas.measureText在单测那边表现为只返回字符串的字符个数length，而非字符串文本宽度，所以需要去mock这个方法。
写法参考的是这个问题中来自Brian Adams例子：
https://stackoverflow.com/questions/39755439/how-to-mock-imported-named-function-in-jest-when-module-is-unmocked

2022-05-13 08:53 UTC, weareoutman commented on bricks/forms/src/general-select/GeneralSelect.tsx
> +import * as GeneralSelectModule from "./GeneralSelect";
那你可以把 `getSelectWidth` 这个函数拎出来放到单独的文件里呀。

2022-05-17 06:10 UTC, closed without merging