feat(): support update route or template
easyops-cn/next-basics pull request #2172
Opened 2023-04-19 01:57 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-04-19 07:01 UTC, weareoutman requested changes

2023-04-19 07:01 UTC, weareoutman commented on bricks/next-builder/src/data-providers/UpdateBricks.ts
> +      node.properties?.replace(/(?<=\s)TPL(?!\w)/g, "STATE") ?? "{}"
进行表达式替换，最好参考 [replaceWidgetFunctions](https://github.com/easyops-cn/next-basics/blob/960fd81b65108fb6f9bec42137b7a76e199b1853/bricks/next-builder/src/data-providers/utils/replaceWidgetFunctions.ts) 的实现进行基于 AST 的替换。

2023-04-19 07:06 UTC, weareoutman commented on bricks/next-builder/src/data-providers/UpdateBricks.ts
> +      node.properties?.replace(/(?<=\s)TPL(?!\w)/g, "STATE") ?? "{}"
另外注意 JS RegExp 的 lookbehind 有浏览器要求，[chrome >= 62](https://caniuse.com/js-regexp-lookbehind)，不在我们的兼容列表内

2023-04-19 07:13 UTC, SailorF commented on bricks/next-builder/src/data-providers/UpdateBricks.spec.ts
> +            transform: "list",
可以，测试用例问题

2023-04-19 07:16 UTC, SailorF commented
> 这里每一种替换都有不同的风险，建议在交互上可以：
> 
> * 提供勾选项，每一种替换类型（例如 useResolves, template proxy, TPL -> STATE 等）开发者可以自行打勾，勾上的才进行替换；
> * 提供修改预览，即在真的执行替换前，给出一个 diff 之类的预览给开发者看，然后再由开发者决定是否执行替换。如果更近一步，这里预览也是一个可勾选的清单，开发者可以打勾来决定执行哪些替换。

目前还没有实现页面交互这块，后续可以考虑

2023-04-20 02:27 UTC, weareoutman commented on bricks/next-builder/src/data-providers/UpdateBricks.ts
> +          if ($1.trim().startsWith("track")) return match;
这个有点问题，应该是 `startsWith('"track ') || startsWith("'track ")`

2023-04-20 02:28 UTC, weareoutman commented on bricks/next-builder/src/data-providers/UpdateBricks.ts
> +          if ($1.trim().startsWith("track")) return match;
另外，最好也根据 AST 来做处理，这里可以在上面的 chunks 中 push 一个 `"track state",`，而不是用正则替换。

2023-04-20 03:31 UTC, weareoutman approved these changes

2023-04-20 03:32 UTC, merged