fix(): mock uid error
easyops-cn/next-basics pull request #2345
Opened 2023-06-27 10:39 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [x] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [x] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2023-06-27 11:07 UTC, weareoutman commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
这样含有点号了哦。用 `uniqueId` 有啥问题？

2023-06-27 11:09 UTC, SailorF commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
这里 uniqueId 生产的 id 与我们自己的 uid 产生冲突了，导致新增构件时，由于 uid  识别问题，导致树渲染错误

2023-06-27 11:10 UTC, SailorF commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
含点号也问题不大？ 或者我 x 10000 ？

2023-06-28 00:39 UTC, weareoutman commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
不是还有前缀吗，为啥会冲突呢？

2023-06-28 01:46 UTC, SailorF commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
uid时没有前缀的，instanceId，id才有；调试看到的情况是，通过 uniqueId 生成的 id 跟我们自己树上面的 uid 冲突了，所以才改成了随机数

2023-06-28 01:54 UTC, weareoutman commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
应该改成调这个 api

<img width="499" alt="image" src="https://github.com/easyops-cn/next-basics/assets/2338946/f35dabeb-11fa-4290-a59d-27006aec64dd">

2023-06-28 01:55 UTC, weareoutman commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +    const nodeId = `mock_id_${nodeUid}`;
目前没有 export，先 export 出来

2023-06-28 03:16 UTC, weareoutman commented on bricks/presentational-bricks/CHANGELOG.md
> -
还原下这个文件吧

2023-06-28 03:20 UTC, weareoutman approved these changes

2023-06-28 03:21 UTC, weareoutman requested changes

2023-06-28 03:21 UTC, weareoutman commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +  getUniqueNodeId,
需要更新依赖

2023-06-28 03:23 UTC, SailorF commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +  getUniqueNodeId,
依赖已经更新到主干上去了

2023-06-28 03:24 UTC, weareoutman commented on bricks/next-builder/src/workbench-cache-action/WorkbenchCacheAction.tsx
> +  getUniqueNodeId,
构件包对 brick_next 的依赖声明哦

2023-06-28 03:26 UTC, weareoutman approved these changes

2023-06-28 03:40 UTC, merged