feat(time): new package time & new brick task-calendar
easyops-cn/next-basics pull request #464
Opened 2021-06-23 07:24 UTC by Nlicroshan

Closes BRICK_STORE-2160

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [x] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [x] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2021-06-23 07:49 UTC, weareoutman commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +import { PickerPanel } from "rc-picker";
为啥使用了 rc-picker，antd 没有对应接口吗？

2021-06-23 08:07 UTC, Nlicroshan commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +import { PickerPanel } from "rc-picker";
antd 只有 `Calendar ` 可以自定义单元格，但这个构件的头部和切换效果跟预期不太一致，就使用了rc-picker

2021-06-23 08:19 UTC, weareoutman commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +import { PickerPanel } from "rc-picker";
我看头部有 `headerRender` 呀？使用底层的 rc-picker 会带来 antd 的一些统一配置和样式的相关能力的缺失，比如 locale 的统一配置等。
![image](https://user-images.githubusercontent.com/2338946/123061909-a4084b80-d43e-11eb-8e06-81b72b2ed38e.png)

2021-06-23 09:14 UTC, weareoutman requested changes

2021-06-23 09:14 UTC, weareoutman commented on bricks/time/package.json
> +    "rc-picker": "^2.5.1"
rc-picker 没有使用了的话需要移除并重新 yarn。

2021-06-23 09:15 UTC, weareoutman commented on bricks/time/package.json
> +    "rc-picker": "^2.5.1"
除了这个问题，我没有其它问题了，请 @willc001 继续 Review。

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +  briefData?: BriefData[];
变量名上最好还是体现一下是数组吧

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +            {selectedData?.date?.format("YYYY[年]MM[月]DD[日]")}
这里应该要考虑国际化吧

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +    data?: { brief: any; task: any; importance: any };
我看下面的 `setSelectedData` 都会同时时设置 `date` 和 `data`，这里应该不用标为可选吧，这样下面也不需要用 optional chaining 来取 `date` 和 `data`

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +    return (
这部分感觉要有 `selectedData` 才有值，不如先判断有没有 `selectedData`，这样可以少用很多 optional chaining

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +            {selectedData?.data?.importance?.map((issues) => (
我看这个 `importance` 也是一定会有的，最好还是只在有可能没有的情况下使用 optional chaining，以提高性能，减少生成产物体积。
ref: https://dev.to/smeijer/the-costs-of-optional-chaining-5bno

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/TaskCalendar.tsx
> +                const taskTime = get(task, taskSettings?.fields?.time);
这块看起来也都是依赖 `taskSettings` 的数据，要不先判断有没有 `taskSettings`？

2021-06-23 11:37 UTC, willc001 commented on bricks/time/src/task-calendar/index.tsx
> +  calendarOnSelect: EventEmitter<{ date: string; data?: Record<string, any> }>;
`{ date: string; data?: Record<string, any> }` 这个类型看起来出现了很多次，可以提成一个类型来统一，方便维护

2021-06-24 02:53 UTC, willc001 approved these changes

2021-06-24 03:45 UTC, weareoutman approved these changes

2021-06-24 03:45 UTC, merged