Sailor/master/use children
easyops-cn/next-basics pull request #556
Opened 2021-07-15 10:18 UTC by SailorF

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

添加了useChildren特性

2021-07-15 12:13 UTC, weareoutman requested changes

2021-07-15 12:13 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +        Object.prototype.toString.call(v) === "[object Object]"
注意使用 `Object.create(null)` 创建的对象是没有 `prototype` 的，这里建议参考其它地方统一用 `import { isObject } from "@next-core/brick-utils"` 来判断一个数据是否是非 null 对象。

2021-07-15 12:13 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +      if (k === "useChildren" && /\[.*?\]/.test(String(v))) {
初期先严格限制下正则吧，建议用 `/^\[\w+\]$/` （加上头尾控制、并限制有效字符）。

2021-07-15 12:13 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +      if (k === "useChildren" && /\[.*?\]/.test(String(v))) {
另外这里应该先要求 `typeof v === "string"` 而不是对它进行类型转换。

2021-07-15 12:13 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +          delete conf.useChildren;
还应该执行下 `delete slots[v]` 吧？

2021-07-15 12:13 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +          conf.useBrick = (matchUseChild as SlotConfOfBricks).bricks[0];
`useBrick` 也可以为数组的，不过有少数构件仅支持单个配置，这里可以判断 `brick.length === 1` 时取 `[0]`，否则用整个数组。

2021-07-15 12:14 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.spec.ts
> +    expect(buildStoryboard(input)).toMatchObject(output);
建议保留 `toEqual` 以进行严格断言。

2021-07-16 01:51 UTC, SailorF commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +function setUseChild(parentConf: BrickConf, slots: SlotsConf) {
对, 忘记改了

2021-07-16 02:02 UTC, SailorF commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +      if (k === "useChildren" && /\[.*?\]/.test(String(v))) {
我添加上头尾控制吧, 内容匹配应该更加灵活的

2021-07-16 02:09 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +          conf.useBrick = (matchUseChild as SlotConfOfBricks).bricks[0];
但是我感觉按现在的逻辑是在单个子构件 mount 时来查找 useChildren 的，这可能导致一个问题。

假设 useChildren 关联了两个子构件，那么在第一个子构件 mount 时，父构件的 `useChildren` 就被删除了，这会导致第二个子构件 mount 时，丢失了 `useChildren` 的信息。你可以添加一个测试用例看看是否有这个问题。

2021-07-16 02:10 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +      if (k === "useChildren" && /\[.*?\]/.test(String(v))) {
不需要灵活，初期加多限制，后面有需要可以放开；如果初期就放开了，后面收不回来。

2021-07-16 02:12 UTC, SailorF commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +      if (k === "useChildren" && /\[.*?\]/.test(String(v))) {
好的

2021-07-16 02:13 UTC, SailorF commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +          conf.useBrick = (matchUseChild as SlotConfOfBricks).bricks[0];
有可能会, 我测试一下

2021-07-16 02:31 UTC, SailorF commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +          conf.useBrick = (matchUseChild as SlotConfOfBricks).bricks[0];
测试了一下, 方法需要重新, 数组场景未考虑到

2021-07-16 07:34 UTC, weareoutman commented on bricks/next-builder/src/shared/storyboard/buildStoryboard.ts
> +  setUseChild(parentConf?.properties, parentConf?.slots);
这两个 `?.` 是多余的。

2021-07-16 07:41 UTC, weareoutman approved these changes

2021-07-16 07:51 UTC, merged