feat(): support images to compress and support detele un use images
easyops-cn/next-basics pull request #847
Opened 2021-11-16 12:57 UTC by SailorF

Refs: NEXT_BUILDER-1113

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [x] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [x] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [x] 给新特性添加了单元测试。
- [x] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

Markdown图片上传默认压缩, 增加删除项目无用图片功能

2021-11-17 08:33 UTC, weareoutman requested changes

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/package.json
> +    "@next-sdk/object-store-sdk": "^2.1.2",
使用了后台组件新版本，更新了依赖吗？PR 的检查项勾对了吗？

2021-11-17 08:33 UTC, weareoutman commented on bricks/presentational-bricks/package.json
> +    "@next-sdk/object-store-sdk": "^2.1.2",
依赖问题同上。

2021-11-17 08:33 UTC, weareoutman commented on bricks/presentational-bricks/src/markdown-editor/MarkdownEditor.tsx
> +            height: useMinSize ? 768 : height / 2,
这里前端不用管这里图片的尺寸，只需要给后台一个 `width/height` 的最大界限值就好了吧？

另外 1024/768 的限制有点小了，建议这样：
```suggestion
            width: 1280,
            height: 800,
```

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +import {
你这个 images compress 和 delete unused images 这两个需求比较独立，下次注意分两个 PR 分开提。

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +  "next-builder.provider-delete-unuse-images",
```suggestion
  "next-builder.provider-delete-unused-images",
```

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +    fields: { from: true, name: true, url: true },
`from, name` 这两个字段没有用到吧？

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +    query: { "project.instanceId": projectId, name: { $like: "%%" } },
`name: { $like: "%%" }` 这个参数是多余的。

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +    const match = str.match(createRegRule());
这个比较的效率不太高吧？每次都要创建一个正则表达式。另外如果图片数量过多，这个正则表达式的性能应该不一定好。

2021-11-17 08:33 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +  walk(storyboard);
walk storyboard 要兼容新支持的语法，所以这个 PR 合了之后也先不要发布「delete unused images」的这个特性，等我晚些调整下这里的逻辑。

2021-11-18 02:32 UTC, SailorF commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +  walk(storyboard);
好

2021-11-18 06:24 UTC, weareoutman requested changes

2021-11-18 06:24 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +    /\/next\/api\/gateway\/object_store.object_store.GetObject\/api\/v1\/objectStore\/bucket\/next-builder\/object\/[^/](.+[png|jpg|jpeg|gif])/g;
这个正则的最后部分可能有问题，最好这样：

```js
...\/object\/.+?\.(?:png|jpe?g|gif)
             ^^^
             // Non-greedy matching
             // See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Quantifiers#greedy_versus_non-greedy)
```

你可以加一个测试用例，让文档内容含有多个图片地址（且不含换行符）。

2021-11-18 06:24 UTC, weareoutman commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +];
这是啥？

2021-11-18 06:28 UTC, SailorF commented on bricks/next-builder/src/data-providers/DeleteUnusedImages.ts
> +];
测试数据忘记删了, 我删下

2021-11-18 06:49 UTC, weareoutman approved these changes

2021-11-18 06:56 UTC, merged