feat(): 丰富接口异常情况页面错误处理
easyops-cn/next-basics pull request #876
Opened 2021-12-05 07:39 UTC by MJmajiong

## 依赖检查

组件之间的依赖声明，是微服务组件架构下的重要信息，请确保其正确性。

请勾选以下两组选项其中之一：

- [ ] 本次 MR **没有使用**上游组件（例如框架、后台组件等）的较新版本提供的特性。

或者：

- [ ] 本次 MR **使用了**上游组件（例如框架、后台组件等）的较新版本提供的特性。
- [ ] 在对应的文件中更新了该上游组件的依赖版本（或确认了当前声明的依赖版本已包含本次 MR 使用的新特性）。

## 提交信息检查

Git 提交信息将决定包的版本发布及自动生成的 CHANGELOG，请检查工作内容与提交信息是否相符，并在以下每组选项中都依次确认。

> 破坏性变更是针对于下游使用者而言，可以通过本次改动对下游使用者的影响来识别变更类型：
>
> - 下游使用者不做任何改动，仍可以正常工作时，那么它属于普通变更。
> - 反之，下游使用者不做改动就无法正常工作时，那么它属于破坏性变更。
>
> 例如，构件修改了一个属性名，小产品 Storyboard 中需要使用新属性名才能工作，那么它就是破坏性变更。
> 又例如，构件还没有任何下游使用者，那么它的任何变更都是普通变更。

### 破坏性变更：

- [ ] ⚠️ 本次 MR 包含**破坏性变更**的提交，请继续确认以下所有选项：
- [ ] 没有更好的兼容方案，必须做破坏性变更。
- [ ] 使用了 `feat` 作为提交类型。
- [ ] 标注了 `BREAKING CHANGE: 你的变更说明`。
- [ ] 同时更新了本仓库中所有下游使用者的调用。
- [ ] 同时更新了本仓库中所有下游使用者对该子包的依赖为即将发布的 major 版本。
- [ ] 同时为其它仓库的 Migrating 做好了准备，例如文档或批量改动的方法。
- [ ] 手动验证过破坏性变更在 Migrate 后可以正常工作。
- [ ] 破坏性变更所在的提交没有意外携带其它子包的改动。

### 新特性：

- [ ] 本次 MR 包含新特性的提交，且该提交不带有破坏性变更，并使用了 `feat` 作为提交类型。
- [ ] 给新特性添加了单元测试。
- [ ] 手动验证过新特性可以正常工作。

### 问题修复：

- [ ] 本次 MR 包含问题修复的提交，且该提交不带有新特性或破坏性变更，并使用了 `fix` 作为提交类型。
- [ ] 给问题修复添加了单元测试。
- [ ] 手动验证过问题修复得到解决。

### 杂项工作：

即所有对下游使用者无任何影响、且没有必要显示在 CHANGELOG 中的改动，例如修改注释、测试用例、开发文档等：

- [ ] 本次 MR 包含杂项工作的提交，且该提交不带有问题修复、新特性或破坏性变更，并使用了 `chore`, `docs`, `test` 等作为提交类型。

2021-12-06 08:40 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +const FORBIDDEN = "403";
这里可以用个枚举，上面 `CategoryType` 的 `key` 的类型就可以直接用这个枚举

2021-12-06 08:40 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +  const isException: boolean = Object.keys(httpCodeObj).includes(props.code);
这里不用这么麻烦吧，直接在 `httpCodeObj` 上取 `props.code`，判断下有没有就可以了

2021-12-06 08:40 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +  const isException: boolean = Object.keys(httpCodeObj).includes(props.code);
最好不要用 Obj 这种意义不明的命名，比如说这里可以命名为 `httpCodeIllustrationMap`

2021-12-06 08:40 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +          name={httpCodeObj[props.code]?.name}
这里多次用到 `httpCodeObj[props.code]` 的值，可以缓存到变量，这样也不需要单独的 `isException` 变量了，直接判断缓存的这个变量就行，而且也不需要 optional chaining

2021-12-06 08:40 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +          name={httpCodeObj[props.code]?.name}
这里多次用到 `httpCodeObj[props.code]` 的值，可以缓存到变量，这样也不需要单独的 `isException` 变量了，直接判断缓存的这个变量就行，而且也不需要 optional chaining

2021-12-06 14:16 UTC, MJmajiong commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +          name={httpCodeObj[props.code]?.name}
已修改

2021-12-06 14:16 UTC, MJmajiong commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +  const isException: boolean = Object.keys(httpCodeObj).includes(props.code);
已修改

2021-12-06 14:16 UTC, MJmajiong commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +const FORBIDDEN = "403";
已修改

2021-12-07 01:17 UTC, weareoutman requested changes

2021-12-07 01:17 UTC, weareoutman commented on bricks/basic-bricks/src/page-error/index.tsx
> +  code: string;
```suggestion
  @property({ type: Number })
  code: number;
```

2021-12-07 01:18 UTC, weareoutman commented on yarn.lock
> +  integrity sha512-HWT4hCEDeqlIPpgUpgVIWNSZ3sTdqQ6cchw/vPkx9sOYzX0thP/FPxfAvbb1KgrqnbKvJZZnEUuWmUTDIOXlhg==
不要手动更新 `@next-core/*`，交给机器人。手动更新会有遗漏。

2021-12-07 01:34 UTC, weareoutman commented on yarn.lock
> +  integrity sha512-HWT4hCEDeqlIPpgUpgVIWNSZ3sTdqQ6cchw/vPkx9sOYzX0thP/FPxfAvbb1KgrqnbKvJZZnEUuWmUTDIOXlhg==
#875 已经合并，你需要先重置下 yarn.lock 再 rebase 下主干。

```bash
git fetch --prune
git checkout origin/master -- yarn.lock
git rebase origin/master
```

2021-12-07 01:54 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +import { BrickIllustration } from "../../../presentational-bricks/src/brick-illustration/BrickIllustration";
不要跨包用相对路径引用，这里可以把 `BrickIllustration` 提到 libs 包里

2021-12-07 01:55 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +  const httpCodeItem: ItemHttpType = httpCodeIllustrationMap[props.code];
这里应该有类型推断，不用主动声明类型

2021-12-07 01:55 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +    title: "无访问权限",
这些文本加个国际化吧

2021-12-07 01:58 UTC, willc001 commented on bricks/basic-bricks/src/page-error/PageError.tsx
> +          name={httpCodeItem?.name}
当 `isException` 为 true 时，`httpCodeItem` 一定存在，不需要用 optional chaining

2021-12-07 03:48 UTC, willc001 approved these changes

2021-12-07 04:08 UTC, weareoutman approved these changes

2021-12-07 04:08 UTC, merged